/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module addsub_16bit(a, b, m, sum, c_out);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input m;
  wire m;
  output [15:0] sum;
  wire [15:0] sum;
  output c_out;
  wire c_out;
  wire [15:0] bxor;
  wire [16:0] c;
  assign bxor = b ^ { m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m };
  full_adder \addsub_loop[0].addsub_inst  (
    .a(a[0]),
    .b(bxor[0]),
    .c(m),
    .carry(c[1]),
    .sum(sum[0])
  );
  full_adder \addsub_loop[10].addsub_inst  (
    .a(a[10]),
    .b(bxor[10]),
    .c(c[10]),
    .carry(c[11]),
    .sum(sum[10])
  );
  full_adder \addsub_loop[11].addsub_inst  (
    .a(a[11]),
    .b(bxor[11]),
    .c(c[11]),
    .carry(c[12]),
    .sum(sum[11])
  );
  full_adder \addsub_loop[12].addsub_inst  (
    .a(a[12]),
    .b(bxor[12]),
    .c(c[12]),
    .carry(c[13]),
    .sum(sum[12])
  );
  full_adder \addsub_loop[13].addsub_inst  (
    .a(a[13]),
    .b(bxor[13]),
    .c(c[13]),
    .carry(c[14]),
    .sum(sum[13])
  );
  full_adder \addsub_loop[14].addsub_inst  (
    .a(a[14]),
    .b(bxor[14]),
    .c(c[14]),
    .carry(c[15]),
    .sum(sum[14])
  );
  full_adder \addsub_loop[15].addsub_inst  (
    .a(a[15]),
    .b(bxor[15]),
    .c(c[15]),
    .carry(c_out),
    .sum(sum[15])
  );
  full_adder \addsub_loop[1].addsub_inst  (
    .a(a[1]),
    .b(bxor[1]),
    .c(c[1]),
    .carry(c[2]),
    .sum(sum[1])
  );
  full_adder \addsub_loop[2].addsub_inst  (
    .a(a[2]),
    .b(bxor[2]),
    .c(c[2]),
    .carry(c[3]),
    .sum(sum[2])
  );
  full_adder \addsub_loop[3].addsub_inst  (
    .a(a[3]),
    .b(bxor[3]),
    .c(c[3]),
    .carry(c[4]),
    .sum(sum[3])
  );
  full_adder \addsub_loop[4].addsub_inst  (
    .a(a[4]),
    .b(bxor[4]),
    .c(c[4]),
    .carry(c[5]),
    .sum(sum[4])
  );
  full_adder \addsub_loop[5].addsub_inst  (
    .a(a[5]),
    .b(bxor[5]),
    .c(c[5]),
    .carry(c[6]),
    .sum(sum[5])
  );
  full_adder \addsub_loop[6].addsub_inst  (
    .a(a[6]),
    .b(bxor[6]),
    .c(c[6]),
    .carry(c[7]),
    .sum(sum[6])
  );
  full_adder \addsub_loop[7].addsub_inst  (
    .a(a[7]),
    .b(bxor[7]),
    .c(c[7]),
    .carry(c[8]),
    .sum(sum[7])
  );
  full_adder \addsub_loop[8].addsub_inst  (
    .a(a[8]),
    .b(bxor[8]),
    .c(c[8]),
    .carry(c[9]),
    .sum(sum[8])
  );
  full_adder \addsub_loop[9].addsub_inst  (
    .a(a[9]),
    .b(bxor[9]),
    .c(c[9]),
    .carry(c[10]),
    .sum(sum[9])
  );
  assign { c[16], c[0] } = { c_out, m };
endmodule

module full_adder(a, b, c, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output sum;
  wire sum;
  output carry;
  wire carry;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign _00_ = a & b;
  assign _01_ = b & c;
  assign _02_ = c & a;
  assign _03_ = _00_ | _01_;
  assign carry = _03_ | _02_;
  assign _04_ = a ^ b;
  assign sum = _04_ ^ c;
endmodule
