/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module addsub_16bit(a, b, m, sum, c_out);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input m;
  wire m;
  output [15:0] sum;
  wire [15:0] sum;
  output c_out;
  wire c_out;
  wire [15:0] bxor;
  wire [16:0] c;
  assign bxor = b ^ { m, m, m, m, m, m, m, m, m, m, m, m, m, m, m, m };
  full_adder \addsub_loop[0].addsub_inst  (
    .a(a[0]),
    .b(bxor[0]),
    .c(m),
    .carry(c[1]),
    .sum(sum[0])
  );
  full_adder \addsub_loop[10].addsub_inst  (
    .a(a[10]),
    .b(bxor[10]),
    .c(c[10]),
    .carry(c[11]),
    .sum(sum[10])
  );
  full_adder \addsub_loop[11].addsub_inst  (
    .a(a[11]),
    .b(bxor[11]),
    .c(c[11]),
    .carry(c[12]),
    .sum(sum[11])
  );
  full_adder \addsub_loop[12].addsub_inst  (
    .a(a[12]),
    .b(bxor[12]),
    .c(c[12]),
    .carry(c[13]),
    .sum(sum[12])
  );
  full_adder \addsub_loop[13].addsub_inst  (
    .a(a[13]),
    .b(bxor[13]),
    .c(c[13]),
    .carry(c[14]),
    .sum(sum[13])
  );
  full_adder \addsub_loop[14].addsub_inst  (
    .a(a[14]),
    .b(bxor[14]),
    .c(c[14]),
    .carry(c[15]),
    .sum(sum[14])
  );
  full_adder \addsub_loop[15].addsub_inst  (
    .a(a[15]),
    .b(bxor[15]),
    .c(c[15]),
    .carry(c_out),
    .sum(sum[15])
  );
  full_adder \addsub_loop[1].addsub_inst  (
    .a(a[1]),
    .b(bxor[1]),
    .c(c[1]),
    .carry(c[2]),
    .sum(sum[1])
  );
  full_adder \addsub_loop[2].addsub_inst  (
    .a(a[2]),
    .b(bxor[2]),
    .c(c[2]),
    .carry(c[3]),
    .sum(sum[2])
  );
  full_adder \addsub_loop[3].addsub_inst  (
    .a(a[3]),
    .b(bxor[3]),
    .c(c[3]),
    .carry(c[4]),
    .sum(sum[3])
  );
  full_adder \addsub_loop[4].addsub_inst  (
    .a(a[4]),
    .b(bxor[4]),
    .c(c[4]),
    .carry(c[5]),
    .sum(sum[4])
  );
  full_adder \addsub_loop[5].addsub_inst  (
    .a(a[5]),
    .b(bxor[5]),
    .c(c[5]),
    .carry(c[6]),
    .sum(sum[5])
  );
  full_adder \addsub_loop[6].addsub_inst  (
    .a(a[6]),
    .b(bxor[6]),
    .c(c[6]),
    .carry(c[7]),
    .sum(sum[6])
  );
  full_adder \addsub_loop[7].addsub_inst  (
    .a(a[7]),
    .b(bxor[7]),
    .c(c[7]),
    .carry(c[8]),
    .sum(sum[7])
  );
  full_adder \addsub_loop[8].addsub_inst  (
    .a(a[8]),
    .b(bxor[8]),
    .c(c[8]),
    .carry(c[9]),
    .sum(sum[8])
  );
  full_adder \addsub_loop[9].addsub_inst  (
    .a(a[9]),
    .b(bxor[9]),
    .c(c[9]),
    .carry(c[10]),
    .sum(sum[9])
  );
  assign { c[16], c[0] } = { c_out, m };
endmodule

module alu_16bit(a, b, alu_op, result, carry_out, zero, negative, overflow);
  input [15:0] a;
  wire [15:0] a;
  input [15:0] b;
  wire [15:0] b;
  input [3:0] alu_op;
  wire [3:0] alu_op;
  output [15:0] result;
  wire [15:0] result;
  output carry_out;
  wire carry_out;
  output zero;
  wire zero;
  output negative;
  wire negative;
  output overflow;
  wire overflow;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire [15:0] _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire [15:0] _13_;
  wire _14_;
  wire _15_;
  wire [15:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire [15:0] _27_;
  wire [15:0] _28_;
  wire [15:0] _29_;
  wire [15:0] _30_;
  wire addsub_carry;
  wire [15:0] addsub_result;
  wire [3:0] shift_amt;
  assign _00_ = _10_ & _11_;
  assign _01_ = _00_ & addsub_result[15];
  assign _02_ = a[15] & b[15];
  assign _03_ = _02_ & _12_;
  assign _04_ = a[15] & _11_;
  assign _05_ = _04_ & _12_;
  assign _06_ = _10_ & b[15];
  assign _07_ = _06_ & addsub_result[15];
  assign _08_ = a & b;
  assign _09_ = | { _18_, _17_ };
  assign zero = ! result;
  assign _11_ = ~ b[15];
  assign _12_ = ~ addsub_result[15];
  assign _10_ = ~ a[15];
  assign _13_ = ~ a;
  assign _14_ = _01_ | _03_;
  assign _15_ = _05_ | _07_;
  assign _16_ = a | b;
  function [0:0] _49_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _49_ = b[0:0];
      2'b1?:
        _49_ = b[1:1];
      default:
        _49_ = a;
    endcase
  endfunction
  assign overflow = _49_(1'h0, { _14_, _15_ }, { _18_, _17_ });
  assign carry_out = _09_ ? addsub_carry : 1'h0;
  function [15:0] _51_;
    input [15:0] a;
    input [143:0] b;
    input [8:0] s;
    casez (s) // synopsys parallel_case
      9'b????????1:
        _51_ = b[15:0];
      9'b???????1?:
        _51_ = b[31:16];
      9'b??????1??:
        _51_ = b[47:32];
      9'b?????1???:
        _51_ = b[63:48];
      9'b????1????:
        _51_ = b[79:64];
      9'b???1?????:
        _51_ = b[95:80];
      9'b??1??????:
        _51_ = b[111:96];
      9'b?1???????:
        _51_ = b[127:112];
      9'b1????????:
        _51_ = b[143:128];
      default:
        _51_ = a;
    endcase
  endfunction
  assign result = _51_(16'hxxxx, { a, _29_, _28_, _27_, _13_, _30_, _16_, _08_, addsub_result }, { _19_, _20_, _21_, _22_, _23_, _24_, _25_, _26_, _09_ });
  assign _19_ = alu_op == 4'h9;
  assign _20_ = alu_op == 4'h8;
  assign _21_ = alu_op == 4'h7;
  assign _22_ = alu_op == 4'h6;
  assign _23_ = alu_op == 4'h5;
  assign _24_ = alu_op == 4'h4;
  assign _25_ = alu_op == 4'h3;
  assign _26_ = alu_op == 4'h2;
  assign _17_ = alu_op == 4'h1;
  assign _18_ = ! alu_op;
  assign _27_ = a << b[3:0];
  assign _28_ = a >> b[3:0];
  assign _29_ = $signed(a) >>> b[3:0];
  assign _30_ = a ^ b;
  addsub_16bit addsub_inst (
    .a(a),
    .b(b),
    .c_out(addsub_carry),
    .m(alu_op[0]),
    .sum(addsub_result)
  );
  assign shift_amt = b[3:0];
  assign negative = result[15];
endmodule

module full_adder(a, b, c, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output sum;
  wire sum;
  output carry;
  wire carry;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign _00_ = a & b;
  assign _01_ = b & c;
  assign _02_ = c & a;
  assign _03_ = _00_ | _01_;
  assign carry = _03_ | _02_;
  assign _04_ = a ^ b;
  assign sum = _04_ ^ c;
endmodule
