/* Generated by Yosys 0.66+4 (git sha1 8125af88d-dirty, x86_64-w64-mingw32-g++ 13.2.1 -O3) */

module full_adder(a, b, c, sum, carry);
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output sum;
  wire sum;
  output carry;
  wire carry;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  assign _00_ = a & b;
  assign _01_ = b & c;
  assign _02_ = c & a;
  assign _03_ = _00_ | _01_;
  assign carry = _03_ | _02_;
  assign _04_ = a ^ b;
  assign sum = _04_ ^ c;
endmodule
